name: ci
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取master分支
      - name: Checkout
        uses: actions/checkout@master
      # 设置buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # 登陆dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 编译并且推送到dockerhub
      - name: Build website
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
          tags: |
            bboysoul/octant:latest
            bboysoul/octant:v1.0.0
